services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data 
    ports:
      - 8432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# volumes:
#   pgdata:
